### ISSUE TITLE
XCode error while building

### ISSUE THREAD

**Issue by LeonardoDemartino** [Purchasely/Unity-Package#6]
XCode Version 14.2 (14C18)

```
error: Multiple commands produce '/build/ReleaseForRunning-iphoneos/Application.app/Frameworks/Purchasely.framework'
    note: Target 'Unity-iPhone' (project 'Unity-iPhone') has copy command from '/Pods/Purchasely/Purchasely/Frameworks/Purchasely.xcframework/ios-arm64/Purchasely.framework' to '/build/ReleaseForRunning-iphoneos/Application.app/Frameworks/Purchasely.framework'
    note: That command depends on command in Target 'Unity-iPhone' (project 'Unity-iPhone'): script phase “[CP] Embed Pods Frameworks”
```

If I go to "Build Phases" of the "Unity-iPhone" target and remove Purchasely.xcframework from "Embed Frameworks" the build finish successfuly, but this sounds like a slippery slope and I don't know which problem this could arise in the future.

**Comment by kherembourg** [comment]
Hello @LeonardoDemartino 
Thanks for your report, we are checking internally and will get back to you in the coming days

**Comment by yusufkildan** [comment]
I also encountered the same issue. If you remove the following code from `PurchaselyPostProcessor.cs` script, it works good. You don't have to embed this framework to main target. 

`//project.AddFileToEmbedFrameworks(mainTargetGUID, frameworkPath);`

**Comment by EPIKorial** [comment]
I'm marking this issue as closed since we have successfully addressed the problem. I want to express our gratitude for your thorough testing and valuable suggestions. You were absolutely correct, [yusufkildan](https://github.com/yusufkildan), your solution effectively resolved the issue. We had initially added it to address a different problem that is no longer pertinent.
